# Generated by Django 6.0.4 on 2026-04-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
