# Generated by Django 6.0.4 on 2026-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
